name: flutter_maps_app
description: Create an application using google Maps and BLoC in Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  stream_transform: ^2.1.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    image: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/map_styles/
    - assets/images/
