name: flutter_maps_bloc
description: Create an application using google Maps and BLoC in Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  google_maps_webservice: ^0.0.19
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
